{"name": "test_javaTpoint", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: '../FilesCollected/JavaTPointNotes/Python.txt'", "trace": "test_setup = None\n\n    @allure.description(\"validate login credentials\")\n    @allure.severity(severity_level=\"CRITICAL\")\n    def test_javaTpoint(test_setup):\n        \"\"\"\n    \n        :param test_setup:\n        \"\"\"\n        # Opening JavaTPoint Url\n        driver.get(Urls.JavaTPointUrl)\n        # Wait for Page to Load\n        time.sleep(Constants.TwoSeconds)\n    \n        # Opening Python Tab\n        driver.find_element_by_xpath(Xpaths.PythonTab).click()\n        # Wait for page to load\n        time.sleep(Constants.TwoSeconds)\n    \n        # Going Tab To Tab and extracting notes\n        python_Notes = driver.find_element_by_xpath(Xpaths.PythonNotesJavaTPoint).text\n    \n        # Updating notes in File\n>       fileNotes = open('../FilesCollected/JavaTPointNotes/Python.txt', 'w')\nE       FileNotFoundError: [Errno 2] No such file or directory: '../FilesCollected/JavaTPointNotes/Python.txt'\n\nJavaTPoint.py:44: FileNotFoundError"}, "description": "validate login credentials", "start": 1617599257955, "stop": 1617599413520, "uuid": "0dabf1cf-f627-4c7f-821d-548b34c9ea3c", "historyId": "5f65e9ccf3195d6088d63c403a106cb2", "testCaseId": "3c2fdaacbda1a00f79fbecd5843fcf26", "fullName": "JavaTPoint#test_javaTpoint", "labels": [{"name": "severity", "value": "CRITICAL"}, {"name": "suite", "value": "JavaTPoint"}, {"name": "host", "value": "LAPTOP-H4PCMV9S"}, {"name": "thread", "value": "102976-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "JavaTPoint"}]}